name: condition workflow
on:
  workflow_dispatch:
    inputs:
      versionName:
        required: true
        description: "this is a version name for GH workflow "
  #push:
jobs:
  condition-workflow:
    name: condition workflow
    runs-on: ubuntu-latest
    steps:
     - name: before checkout action
       if: github.ref == 'refs/heads/main'
       run: |
         pwd
         ls -a 
         echo ${{ github.ref }}
       shell: bash
     - name: checkout action
       uses: actions/checkout@v4

     - name: after checkout action
       if: github.event.inputs.versionName == 'test'
       run: |
            pwd
            cd .github/workflows
            ls -a 
            echo ${{ github.ref }}
       shell: bash
