name: cron workflow
on:
  schedule:
    - cron: "*/5 * * * *" 
    #- cron: "*/20 1 * * *"

jobs:
 cron-workflow-job:
   runs-on: ubuntu-latest
   steps:
    - run: echo "schedule workflow"

    - name: debug
      run: |
       echo "Current directory:"
       pwd
       echo "UTC Time:"
       date
