name: first-workflow
on:
  push:
    branches:
      - "main"
jobs:
  fist-workflow-job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: before checkout action
        run: ls
        shell: bash 
      - name: checkout steps
        uses: actions/checkout@v6.0.2
        
      - name: after checkout action
        run: ls
        shell: bash

  