name: first-workflow
on:
  push:
    branches:
      - "main"
jobs:
  fist-workflow-job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: run bash command
        run: echo "first workflow"
        shell: bash 
  