name: receive_dispatch

on:
  repository_dispatch:
    types: [testing]

jobs:
  receive:
    runs-on: ubuntu-latest
    steps:
      - name: Print payload
        run: |
          echo "Ref: ${{ github.event.client_payload.ref }}"
          echo "SHA: ${{ github.event.client_payload.sha }}"
      - name: before checkout action
        run: ls -a 
        shell: bash 
      - name: checkout steps
        uses: actions/checkout@v4
      - name: after checkout action
        run: ls -a 
        shell: bash